### ISSUE TITLE
Runners sometimes fail to set up job with `tar -xzf` error

### ISSUE THREAD

**Issue by samuelburnham** [lurk-lab/gh-actions-runner#7]
This error sometimes happens when setting up a new job:
```
Can't use 'tar -xzf' extract archive file: /tmp/runner/work/_actions/_temp_20cdcd44-5d7c-4cf8-b590-0412f394b59e/157ce330-0a3a-421e-a791-d5e30fd37941.tar.gz. return code: 2.
```
It seems to have started with #6. I haven't yet reproduced on any lurk-lab repos but making a note in case it shows up again.
 
Related issues:
https://github.com/actions/runner/issues/1923
https://github.com/myoung34/docker-github-actions-runner/issues/113

**Comment by huitseeker** [comment]
See https://github.com/lurk-lab/neptune/actions/runs/5623445348/job/15238135340?pr=214
on https://github.com/lurk-lab/neptune/pull/214
